
###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts?sender=Dor

###

GET http://localhost:3000/posts/6741eed9d9d9a2e71f9362cc

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Hello",
    "sender": "Kevin2",
    "content": "Hello World..."
}

###

DELETE http://localhost:3000/posts/676d4ce7b1394c9748f893f3

###

GET http://localhost:3000/comments

###

GET http://localhost:3000/comments?postId=67387912cb100190cd60d144

###

GET http://localhost:3000/comments/6738835b613147878b7ba45f

###

POST http://localhost:3000/comments 
Content-Type: application/json

{
  "sender": "Dor", 
  "postId": "67387912cb100190cd60d145", 
  "content": "This is my first comment"
}

###

DELETE http://localhost:3000/comments/673882b1613147878b7ba45b

###

PUT http://localhost:3000/comments/6738835b613147878b7ba45f
Content-Type: application/json

{
  "sender": "Dor", 
  "postId": "67387912cb100190cd60d144", 
  "content": "This is my second comment"
}


###

GET http://localhost:3000/users

###

GET http://localhost:3000/users?name=Dor

###

GET http://localhost:3000/users/676d4f2cec5ddd46e0314af3

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Dor2",
    "email": "2@.com",
    "password": "123456"
}

###

DELETE http://localhost:3000/users/676d4ff1ec5ddd46e0314aff